// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsFbCZD_PUvR0z3WZGflViKSiXJtcuZDE',
    appId: '1:654317885156:web:77af78a43befe98d67fef1',
    messagingSenderId: '654317885156',
    projectId: 'agriguard-fd327',
    authDomain: 'agriguard-fd327.firebaseapp.com',
    storageBucket: 'agriguard-fd327.firebasestorage.app',
    measurementId: 'G-T6GEFPLEKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGB-UQV5d-BeIHqarvQeDZzBZfuY9V-Xs',
    appId: '1:654317885156:android:1c8a1085ece3d80267fef1',
    messagingSenderId: '654317885156',
    projectId: 'agriguard-fd327',
    storageBucket: 'agriguard-fd327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ__3-m-Q8x80qHyoMrBdwe988Hzmyw0s',
    appId: '1:654317885156:ios:caed04cdff99949767fef1',
    messagingSenderId: '654317885156',
    projectId: 'agriguard-fd327',
    storageBucket: 'agriguard-fd327.firebasestorage.app',
    iosBundleId: 'com.example.agrismart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ__3-m-Q8x80qHyoMrBdwe988Hzmyw0s',
    appId: '1:654317885156:ios:caed04cdff99949767fef1',
    messagingSenderId: '654317885156',
    projectId: 'agriguard-fd327',
    storageBucket: 'agriguard-fd327.firebasestorage.app',
    iosBundleId: 'com.example.agrismart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsFbCZD_PUvR0z3WZGflViKSiXJtcuZDE',
    appId: '1:654317885156:web:e240a6e9ef4a950a67fef1',
    messagingSenderId: '654317885156',
    projectId: 'agriguard-fd327',
    authDomain: 'agriguard-fd327.firebaseapp.com',
    storageBucket: 'agriguard-fd327.firebasestorage.app',
    measurementId: 'G-NGLXEPZZ2Q',
  );
}
